// Builds map.json: Russia and its neighbours as projected SVG paths, plus the projection
// parameters the app uses to place markers. Only needs re-running to change the map itself.
//
//   npm i --no-save world-atlas@2 topojson-client@3 && node plague-tracker/tools/build-map.mjs
//
// Projection: Albers equal-area conic centred on Russia. index.html has the same function.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const LAKES_URL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_50m_lakes.geojson";
const P = { lon0: 100, lat0: 60, lat1: 50, lat2: 70 };
const WIDTH = 1000;

const rad = Math.PI / 180;
const n = (Math.sin(P.lat1 * rad) + Math.sin(P.lat2 * rad)) / 2;
const C = Math.cos(P.lat1 * rad) ** 2 + 2 * n * Math.sin(P.lat1 * rad);
const rho0 = Math.sqrt(C - 2 * n * Math.sin(P.lat0 * rad)) / n;
function albers(lon, lat) {
  if (lon < -20) lon += 360; // keep Chukotka east of the antimeridian
  const rho = Math.sqrt(C - 2 * n * Math.sin(lat * rad)) / n;
  const t = n * (lon - P.lon0) * rad;
  return [rho * Math.sin(t), rho0 - rho * Math.cos(t)];
}

const topo = JSON.parse(readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8"));
const countries = feature(topo, topo.objects.countries).features;
const russia = countries.find((f) => f.properties.name === "Russia");
const lakes = (await (await fetch(LAKES_URL)).json()).features
  .filter((f) => ["Lake Baikal", "Lake Ladoga", "Lake Onega", "Lake Balkhash"].includes(f.properties.name));

const rings = (g) => (g.type === "Polygon" ? g.coordinates : g.type === "MultiPolygon" ? g.coordinates.flat() : []);

// Frame: Russia's bounding box, with room for the southern neighbours.
let [x0, y0, x1, y1] = [Infinity, Infinity, -Infinity, -Infinity];
for (const ring of rings(russia.geometry)) for (const [lon, lat] of ring) {
  const [x, y] = albers(lon, lat);
  x0 = Math.min(x0, x); x1 = Math.max(x1, x); y0 = Math.min(y0, y); y1 = Math.max(y1, y);
}
const padX = (x1 - x0) * 0.02, padTop = (y1 - y0) * 0.02, padBottom = (y1 - y0) * 0.12;
x0 -= padX; x1 += padX; y0 -= padBottom; y1 += padTop;
const k = WIDTH / (x1 - x0);
const HEIGHT = Math.round((y1 - y0) * k);
const tx = -x0 * k, ty = y1 * k;
const toScreen = (lon, lat) => { const [x, y] = albers(lon, lat); return [x * k + tx, -y * k + ty]; };

function pathFor(geometry, minStep = 1.4, minExtent = 3) {
  let d = "";
  for (const ring of rings(geometry)) {
    const pts = [];
    for (const [lon, lat] of ring) {
      const p = toScreen(lon, lat);
      const last = pts[pts.length - 1];
      if (!last || Math.hypot(p[0] - last[0], p[1] - last[1]) >= minStep) pts.push(p);
    }
    if (pts.length < 3) continue;
    const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
    const ext = Math.max(Math.max(...xs) - Math.min(...xs), Math.max(...ys) - Math.min(...ys));
    if (ext < minExtent) continue;
    if (Math.max(...xs) < -50 || Math.min(...xs) > WIDTH + 50 || Math.max(...ys) < -50 || Math.min(...ys) > HEIGHT + 50) continue;
    d += "M" + pts.map((p) => p[0].toFixed(1) + " " + p[1].toFixed(1)).join("L") + "Z";
  }
  return d;
}

const others = countries.filter((f) => f !== russia).map((f) => pathFor(f.geometry, 2.6, 4)).join("");
const out = {
  note: "Generated by tools/build-map.mjs from Natural Earth (public domain) via world-atlas. Do not edit by hand.",
  width: WIDTH,
  height: HEIGHT,
  projection: { ...P, k: +k.toFixed(4), tx: +tx.toFixed(2), ty: +ty.toFixed(2) },
  russia: pathFor(russia.geometry),
  others,
  lakes: lakes.map((f) => ({ name: f.properties.name, d: pathFor(f.geometry, 0.8, 1) })),
};
writeFileSync(join(root, "map.json"), JSON.stringify(out));
console.log(`map.json: ${WIDTH}x${HEIGHT}, ${(JSON.stringify(out).length / 1024).toFixed(0)} KB`);
